spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: chat_app
      username: root
      password: password
      authentication-database: admin

server:
    port: 8080